# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evlzNZSjNNXHXAJxhWQALPHtyhr0MXtr
"""

import streamlit as st
import pandas as pd
import pickle

# Konfigurasi Halaman
st.set_page_config(page_title="Prediksi Harga Rumah", page_icon="🏠")

st.title('🏠 Aplikasi Prediksi Harga Rumah (XGBoost)')

# Load Model
try:
    model = pickle.load(open('house_model.pkl', 'rb'))
except FileNotFoundError:
    st.error("File 'house_model.pkl' belum ada. Upload dulu!")
    st.stop()

# Input User
col1, col2 = st.columns(2)

with col1:
    bhk = st.number_input('Jumlah Kamar (BHK)', min_value=1, value=2)
    sq_ft = st.number_input('Luas Tanah (Sq. Ft)', min_value=100.0, value=1000.0)
    rera = st.selectbox('Terdaftar RERA?', [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")
    under_const = st.selectbox('Sedang Dibangun?', [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")

with col2:
    ready = st.selectbox('Siap Huni?', [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")
    resale = st.selectbox('Bangunan Bekas?', [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")
    long_val = st.number_input('Longitude', value=77.59)
    lat_val = st.number_input('Latitude', value=12.97)

# Tombol Prediksi
if st.button('Hitung Estimasi'):
    # Dataframe Input (Sesuai urutan training di Colab tadi)
    # Kita set POSTED_BY default 1 (Dealer) dan BHK_OR_RK default 1 (BHK)
    input_data = pd.DataFrame({
        'POSTED_BY': [1],
        'UNDER_CONSTRUCTION': [under_const],
        'RERA': [rera],
        'BHK_NO.': [bhk],
        'BHK_OR_RK': [1],
        'SQUARE_FT': [sq_ft],
        'READY_TO_MOVE': [ready],
        'RESALE': [resale],
        'LONGITUDE': [long_val],
        'LATITUDE': [lat_val]
    })

    try:
        prediksi = model.predict(input_data)
        st.success(f"💰 Estimasi Harga: {prediksi[0]:.2f} Lakhs")
    except Exception as e:
        st.error(f"Terjadi kesalahan: {e}")