# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evlzNZSjNNXHXAJxhWQALPHtyhr0MXtr
"""

import streamlit as st
import pandas as pd
import pickle

st.set_page_config(page_title="Prediksi Harga Rumah", page_icon="🏠")
st.title("🏠 Aplikasi Prediksi Harga Rumah")

try:
    model = pickle.load(open('model_house.pkl', 'rb'))
except:
    st.error("File 'model_house.pkl' tidak ditemukan. Jalankan Notebook dulu!")
    st.stop()

st.write("Masukkan detail properti:")
col1, col2 = st.columns(2)

with col1:
    bhk = st.number_input("Jumlah Kamar (BHK)", min_value=1, value=2)
    sq_ft = st.number_input("Luas Area (Sq. Ft)", min_value=100.0, value=1000.0)
    rera = st.selectbox("Terdaftar RERA?", [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")
    under_const = st.selectbox("Sedang Dibangun?", [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")

with col2:
    ready = st.selectbox("Siap Huni?", [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")
    resale = st.selectbox("Bangunan Bekas?", [0, 1], format_func=lambda x: "Ya" if x==1 else "Tidak")
    long = st.number_input("Longitude", value=77.59)
    lat = st.number_input("Latitude", value=12.97)

if st.button("Hitung Estimasi Harga"):
    input_data = pd.DataFrame({
        'POSTED_BY': [1],
        'UNDER_CONSTRUCTION': [under_const],
        'RERA': [rera],
        'BHK_NO.': [bhk],
        'BHK_OR_RK': [0],
        'SQUARE_FT': [sq_ft],
        'READY_TO_MOVE': [ready],
        'RESALE': [resale],
        'ADDRESS': [0],
        'LONGITUDE': [long],
        'LATITUDE': [lat]
    })

    try:
        harga = model.predict(input_data)
        st.success(f"💰 Estimasi Harga: {harga[0]:.2f} Lakhs")
    except Exception as e:
        st.warning("Terjadi ketidakcocokan kolom. Mencoba prediksi ulang dengan kolom yang cocok...")
        try:
             st.error(f"Error detail: {e}")
        except:
             pass